import type { BlogGalleryImage } from '@/types/database'

// Generated by scripts/generate-event-image-manifest.mjs. Do not edit by hand.
export const EVENT_IMAGE_MANIFEST: Record<string, BlogGalleryImage[]> = {
  "photos/april 2025 7th and 8th skardu AKRSP training pilot project": [
    {
      "src": "/images/photos/april%202025%207th%20and%208th%20skardu%20AKRSP%20training%20pilot%20project/1.jpeg",
      "alt": "april 2025 7th and 8th skardu AKRSP training pilot project event photograph 1",
      "caption": null
    },
    {
      "src": "/images/photos/april%202025%207th%20and%208th%20skardu%20AKRSP%20training%20pilot%20project/4.jpeg",
      "alt": "april 2025 7th and 8th skardu AKRSP training pilot project event photograph 2",
      "caption": null
    },
    {
      "src": "/images/photos/april%202025%207th%20and%208th%20skardu%20AKRSP%20training%20pilot%20project/5.jpeg",
      "alt": "april 2025 7th and 8th skardu AKRSP training pilot project event photograph 3",
      "caption": null
    },
    {
      "src": "/images/photos/april%202025%207th%20and%208th%20skardu%20AKRSP%20training%20pilot%20project/6.jpeg",
      "alt": "april 2025 7th and 8th skardu AKRSP training pilot project event photograph 4",
      "caption": null
    },
    {
      "src": "/images/photos/april%202025%207th%20and%208th%20skardu%20AKRSP%20training%20pilot%20project/end.jpeg",
      "alt": "april 2025 7th and 8th skardu AKRSP training pilot project event photograph 5",
      "caption": null
    },
    {
      "src": "/images/photos/april%202025%207th%20and%208th%20skardu%20AKRSP%20training%20pilot%20project/start.jpeg",
      "alt": "april 2025 7th and 8th skardu AKRSP training pilot project event photograph 6",
      "caption": null
    }
  ],
  "photos/avalon school wapda town lahore": [
    {
      "src": "/images/photos/avalon%20school%20wapda%20town%20lahore/1.jpeg",
      "alt": "avalon school wapda town lahore event photograph 1",
      "caption": null
    }
  ],
  "photos/Begining international school teachers holding evaluation sessions": [
    {
      "src": "/images/photos/Begining%20international%20school%20teachers%20holding%20evaluation%20sessions/1.jpeg",
      "alt": "Begining international school teachers holding evaluation sessions event photograph 1",
      "caption": null
    },
    {
      "src": "/images/photos/Begining%20international%20school%20teachers%20holding%20evaluation%20sessions/2.jpeg",
      "alt": "Begining international school teachers holding evaluation sessions event photograph 2",
      "caption": null
    },
    {
      "src": "/images/photos/Begining%20international%20school%20teachers%20holding%20evaluation%20sessions/3.jpeg",
      "alt": "Begining international school teachers holding evaluation sessions event photograph 3",
      "caption": null
    },
    {
      "src": "/images/photos/Begining%20international%20school%20teachers%20holding%20evaluation%20sessions/4.jpeg",
      "alt": "Begining international school teachers holding evaluation sessions event photograph 4",
      "caption": null
    },
    {
      "src": "/images/photos/Begining%20international%20school%20teachers%20holding%20evaluation%20sessions/5.jpeg",
      "alt": "Begining international school teachers holding evaluation sessions event photograph 5",
      "caption": null
    },
    {
      "src": "/images/photos/Begining%20international%20school%20teachers%20holding%20evaluation%20sessions/6.jpeg",
      "alt": "Begining international school teachers holding evaluation sessions event photograph 6",
      "caption": null
    },
    {
      "src": "/images/photos/Begining%20international%20school%20teachers%20holding%20evaluation%20sessions/7.jpeg",
      "alt": "Begining international school teachers holding evaluation sessions event photograph 7",
      "caption": null
    },
    {
      "src": "/images/photos/Begining%20international%20school%20teachers%20holding%20evaluation%20sessions/8.jpeg",
      "alt": "Begining international school teachers holding evaluation sessions event photograph 8",
      "caption": null
    },
    {
      "src": "/images/photos/Begining%20international%20school%20teachers%20holding%20evaluation%20sessions/9.jpeg",
      "alt": "Begining international school teachers holding evaluation sessions event photograph 9",
      "caption": null
    },
    {
      "src": "/images/photos/Begining%20international%20school%20teachers%20holding%20evaluation%20sessions/10.jpeg",
      "alt": "Begining international school teachers holding evaluation sessions event photograph 10",
      "caption": null
    },
    {
      "src": "/images/photos/Begining%20international%20school%20teachers%20holding%20evaluation%20sessions/11.jpeg",
      "alt": "Begining international school teachers holding evaluation sessions event photograph 11",
      "caption": null
    },
    {
      "src": "/images/photos/Begining%20international%20school%20teachers%20holding%20evaluation%20sessions/12.jpeg",
      "alt": "Begining international school teachers holding evaluation sessions event photograph 12",
      "caption": null
    },
    {
      "src": "/images/photos/Begining%20international%20school%20teachers%20holding%20evaluation%20sessions/13.jpeg",
      "alt": "Begining international school teachers holding evaluation sessions event photograph 13",
      "caption": null
    },
    {
      "src": "/images/photos/Begining%20international%20school%20teachers%20holding%20evaluation%20sessions/14.jpeg",
      "alt": "Begining international school teachers holding evaluation sessions event photograph 14",
      "caption": null
    },
    {
      "src": "/images/photos/Begining%20international%20school%20teachers%20holding%20evaluation%20sessions/15.jpeg",
      "alt": "Begining international school teachers holding evaluation sessions event photograph 15",
      "caption": null
    },
    {
      "src": "/images/photos/Begining%20international%20school%20teachers%20holding%20evaluation%20sessions/16.jpeg",
      "alt": "Begining international school teachers holding evaluation sessions event photograph 16",
      "caption": null
    },
    {
      "src": "/images/photos/Begining%20international%20school%20teachers%20holding%20evaluation%20sessions/17.jpeg",
      "alt": "Begining international school teachers holding evaluation sessions event photograph 17",
      "caption": null
    },
    {
      "src": "/images/photos/Begining%20international%20school%20teachers%20holding%20evaluation%20sessions/18.jpeg",
      "alt": "Begining international school teachers holding evaluation sessions event photograph 18",
      "caption": null
    },
    {
      "src": "/images/photos/Begining%20international%20school%20teachers%20holding%20evaluation%20sessions/19.jpeg",
      "alt": "Begining international school teachers holding evaluation sessions event photograph 19",
      "caption": null
    },
    {
      "src": "/images/photos/Begining%20international%20school%20teachers%20holding%20evaluation%20sessions/20.jpeg",
      "alt": "Begining international school teachers holding evaluation sessions event photograph 20",
      "caption": null
    }
  ],
  "photos/Gilgit and hunza training  April 2025 pilot project": [
    {
      "src": "/images/photos/Gilgit%20and%20hunza%20training%20%20April%202025%20pilot%20project/1.jpeg",
      "alt": "Gilgit and hunza training  April 2025 pilot project event photograph 1",
      "caption": null
    },
    {
      "src": "/images/photos/Gilgit%20and%20hunza%20training%20%20April%202025%20pilot%20project/2.jpeg",
      "alt": "Gilgit and hunza training  April 2025 pilot project event photograph 2",
      "caption": null
    },
    {
      "src": "/images/photos/Gilgit%20and%20hunza%20training%20%20April%202025%20pilot%20project/3.jpeg",
      "alt": "Gilgit and hunza training  April 2025 pilot project event photograph 3",
      "caption": null
    },
    {
      "src": "/images/photos/Gilgit%20and%20hunza%20training%20%20April%202025%20pilot%20project/4.jpeg",
      "alt": "Gilgit and hunza training  April 2025 pilot project event photograph 4",
      "caption": null
    },
    {
      "src": "/images/photos/Gilgit%20and%20hunza%20training%20%20April%202025%20pilot%20project/5.jpeg",
      "alt": "Gilgit and hunza training  April 2025 pilot project event photograph 5",
      "caption": null
    },
    {
      "src": "/images/photos/Gilgit%20and%20hunza%20training%20%20April%202025%20pilot%20project/6.jpeg",
      "alt": "Gilgit and hunza training  April 2025 pilot project event photograph 6",
      "caption": null
    },
    {
      "src": "/images/photos/Gilgit%20and%20hunza%20training%20%20April%202025%20pilot%20project/8.jpeg",
      "alt": "Gilgit and hunza training  April 2025 pilot project event photograph 7",
      "caption": null
    },
    {
      "src": "/images/photos/Gilgit%20and%20hunza%20training%20%20April%202025%20pilot%20project/9.jpeg",
      "alt": "Gilgit and hunza training  April 2025 pilot project event photograph 8",
      "caption": null
    },
    {
      "src": "/images/photos/Gilgit%20and%20hunza%20training%20%20April%202025%20pilot%20project/10.jpeg",
      "alt": "Gilgit and hunza training  April 2025 pilot project event photograph 9",
      "caption": null
    },
    {
      "src": "/images/photos/Gilgit%20and%20hunza%20training%20%20April%202025%20pilot%20project/11.jpeg",
      "alt": "Gilgit and hunza training  April 2025 pilot project event photograph 10",
      "caption": null
    },
    {
      "src": "/images/photos/Gilgit%20and%20hunza%20training%20%20April%202025%20pilot%20project/12.jpeg",
      "alt": "Gilgit and hunza training  April 2025 pilot project event photograph 11",
      "caption": null
    },
    {
      "src": "/images/photos/Gilgit%20and%20hunza%20training%20%20April%202025%20pilot%20project/13.jpeg",
      "alt": "Gilgit and hunza training  April 2025 pilot project event photograph 12",
      "caption": null
    },
    {
      "src": "/images/photos/Gilgit%20and%20hunza%20training%20%20April%202025%20pilot%20project/15.jpeg",
      "alt": "Gilgit and hunza training  April 2025 pilot project event photograph 13",
      "caption": null
    },
    {
      "src": "/images/photos/Gilgit%20and%20hunza%20training%20%20April%202025%20pilot%20project/16.jpeg",
      "alt": "Gilgit and hunza training  April 2025 pilot project event photograph 14",
      "caption": null
    },
    {
      "src": "/images/photos/Gilgit%20and%20hunza%20training%20%20April%202025%20pilot%20project/end.jpeg",
      "alt": "Gilgit and hunza training  April 2025 pilot project event photograph 15",
      "caption": null
    },
    {
      "src": "/images/photos/Gilgit%20and%20hunza%20training%20%20April%202025%20pilot%20project/start.jpeg",
      "alt": "Gilgit and hunza training  April 2025 pilot project event photograph 16",
      "caption": null
    },
    {
      "src": "/images/photos/Gilgit%20and%20hunza%20training%20%20April%202025%20pilot%20project/starter.jpeg",
      "alt": "Gilgit and hunza training  April 2025 pilot project event photograph 17",
      "caption": null
    }
  ],
  "photos/gilgit hunza trading session april 2026": [
    {
      "src": "/images/photos/gilgit%20hunza%20trading%20session%20april%202026/1.jpeg",
      "alt": "gilgit hunza trading session april 2026 event photograph 1",
      "caption": null
    },
    {
      "src": "/images/photos/gilgit%20hunza%20trading%20session%20april%202026/2.jpeg",
      "alt": "gilgit hunza trading session april 2026 event photograph 2",
      "caption": null
    },
    {
      "src": "/images/photos/gilgit%20hunza%20trading%20session%20april%202026/3.jpeg",
      "alt": "gilgit hunza trading session april 2026 event photograph 3",
      "caption": null
    },
    {
      "src": "/images/photos/gilgit%20hunza%20trading%20session%20april%202026/4.jpeg",
      "alt": "gilgit hunza trading session april 2026 event photograph 4",
      "caption": null
    },
    {
      "src": "/images/photos/gilgit%20hunza%20trading%20session%20april%202026/13.jpeg",
      "alt": "gilgit hunza trading session april 2026 event photograph 5",
      "caption": null
    },
    {
      "src": "/images/photos/gilgit%20hunza%20trading%20session%20april%202026/14.jpeg",
      "alt": "gilgit hunza trading session april 2026 event photograph 6",
      "caption": null
    },
    {
      "src": "/images/photos/gilgit%20hunza%20trading%20session%20april%202026/15.jpeg",
      "alt": "gilgit hunza trading session april 2026 event photograph 7",
      "caption": null
    },
    {
      "src": "/images/photos/gilgit%20hunza%20trading%20session%20april%202026/16.jpeg",
      "alt": "gilgit hunza trading session april 2026 event photograph 8",
      "caption": null
    },
    {
      "src": "/images/photos/gilgit%20hunza%20trading%20session%20april%202026/17.jpeg",
      "alt": "gilgit hunza trading session april 2026 event photograph 9",
      "caption": null
    },
    {
      "src": "/images/photos/gilgit%20hunza%20trading%20session%20april%202026/18.jpeg",
      "alt": "gilgit hunza trading session april 2026 event photograph 10",
      "caption": null
    },
    {
      "src": "/images/photos/gilgit%20hunza%20trading%20session%20april%202026/19.jpeg",
      "alt": "gilgit hunza trading session april 2026 event photograph 11",
      "caption": null
    },
    {
      "src": "/images/photos/gilgit%20hunza%20trading%20session%20april%202026/20.jpeg",
      "alt": "gilgit hunza trading session april 2026 event photograph 12",
      "caption": null
    },
    {
      "src": "/images/photos/gilgit%20hunza%20trading%20session%20april%202026/21.jpeg",
      "alt": "gilgit hunza trading session april 2026 event photograph 13",
      "caption": null
    },
    {
      "src": "/images/photos/gilgit%20hunza%20trading%20session%20april%202026/22.jpeg",
      "alt": "gilgit hunza trading session april 2026 event photograph 14",
      "caption": null
    }
  ],
  "photos/gujranwala pilot project 2025 fall evaluation team": [
    {
      "src": "/images/photos/gujranwala%20pilot%20project%202025%20fall%20evaluation%20team/1.jpeg",
      "alt": "gujranwala pilot project 2025 fall evaluation team event photograph 1",
      "caption": null
    },
    {
      "src": "/images/photos/gujranwala%20pilot%20project%202025%20fall%20evaluation%20team/2.jpeg",
      "alt": "gujranwala pilot project 2025 fall evaluation team event photograph 2",
      "caption": null
    },
    {
      "src": "/images/photos/gujranwala%20pilot%20project%202025%20fall%20evaluation%20team/3.jpeg",
      "alt": "gujranwala pilot project 2025 fall evaluation team event photograph 3",
      "caption": null
    },
    {
      "src": "/images/photos/gujranwala%20pilot%20project%202025%20fall%20evaluation%20team/7.jpeg",
      "alt": "gujranwala pilot project 2025 fall evaluation team event photograph 4",
      "caption": null
    },
    {
      "src": "/images/photos/gujranwala%20pilot%20project%202025%20fall%20evaluation%20team/9.jpeg",
      "alt": "gujranwala pilot project 2025 fall evaluation team event photograph 5",
      "caption": null
    },
    {
      "src": "/images/photos/gujranwala%20pilot%20project%202025%20fall%20evaluation%20team/10.jpeg",
      "alt": "gujranwala pilot project 2025 fall evaluation team event photograph 6",
      "caption": null
    },
    {
      "src": "/images/photos/gujranwala%20pilot%20project%202025%20fall%20evaluation%20team/11.jpeg",
      "alt": "gujranwala pilot project 2025 fall evaluation team event photograph 7",
      "caption": null
    },
    {
      "src": "/images/photos/gujranwala%20pilot%20project%202025%20fall%20evaluation%20team/15.jpeg",
      "alt": "gujranwala pilot project 2025 fall evaluation team event photograph 8",
      "caption": null
    },
    {
      "src": "/images/photos/gujranwala%20pilot%20project%202025%20fall%20evaluation%20team/16.jpeg",
      "alt": "gujranwala pilot project 2025 fall evaluation team event photograph 9",
      "caption": null
    },
    {
      "src": "/images/photos/gujranwala%20pilot%20project%202025%20fall%20evaluation%20team/19.jpeg",
      "alt": "gujranwala pilot project 2025 fall evaluation team event photograph 10",
      "caption": null
    },
    {
      "src": "/images/photos/gujranwala%20pilot%20project%202025%20fall%20evaluation%20team/20.jpeg",
      "alt": "gujranwala pilot project 2025 fall evaluation team event photograph 11",
      "caption": null
    },
    {
      "src": "/images/photos/gujranwala%20pilot%20project%202025%20fall%20evaluation%20team/21.jpeg",
      "alt": "gujranwala pilot project 2025 fall evaluation team event photograph 12",
      "caption": null
    },
    {
      "src": "/images/photos/gujranwala%20pilot%20project%202025%20fall%20evaluation%20team/22.jpeg",
      "alt": "gujranwala pilot project 2025 fall evaluation team event photograph 13",
      "caption": null
    },
    {
      "src": "/images/photos/gujranwala%20pilot%20project%202025%20fall%20evaluation%20team/23.jpeg",
      "alt": "gujranwala pilot project 2025 fall evaluation team event photograph 14",
      "caption": null
    },
    {
      "src": "/images/photos/gujranwala%20pilot%20project%202025%20fall%20evaluation%20team/24.jpeg",
      "alt": "gujranwala pilot project 2025 fall evaluation team event photograph 15",
      "caption": null
    },
    {
      "src": "/images/photos/gujranwala%20pilot%20project%202025%20fall%20evaluation%20team/26.jpeg",
      "alt": "gujranwala pilot project 2025 fall evaluation team event photograph 16",
      "caption": null
    },
    {
      "src": "/images/photos/gujranwala%20pilot%20project%202025%20fall%20evaluation%20team/27.jpeg",
      "alt": "gujranwala pilot project 2025 fall evaluation team event photograph 17",
      "caption": null
    },
    {
      "src": "/images/photos/gujranwala%20pilot%20project%202025%20fall%20evaluation%20team/28.jpeg",
      "alt": "gujranwala pilot project 2025 fall evaluation team event photograph 18",
      "caption": null
    },
    {
      "src": "/images/photos/gujranwala%20pilot%20project%202025%20fall%20evaluation%20team/888.jpeg",
      "alt": "gujranwala pilot project 2025 fall evaluation team event photograph 19",
      "caption": null
    },
    {
      "src": "/images/photos/gujranwala%20pilot%20project%202025%20fall%20evaluation%20team/2222.jpeg",
      "alt": "gujranwala pilot project 2025 fall evaluation team event photograph 20",
      "caption": null
    },
    {
      "src": "/images/photos/gujranwala%20pilot%20project%202025%20fall%20evaluation%20team/22222222.jpeg",
      "alt": "gujranwala pilot project 2025 fall evaluation team event photograph 21",
      "caption": null
    },
    {
      "src": "/images/photos/gujranwala%20pilot%20project%202025%20fall%20evaluation%20team/11111111111.jpeg",
      "alt": "gujranwala pilot project 2025 fall evaluation team event photograph 22",
      "caption": null
    },
    {
      "src": "/images/photos/gujranwala%20pilot%20project%202025%20fall%20evaluation%20team/sqsqssaza.jpeg",
      "alt": "gujranwala pilot project 2025 fall evaluation team event photograph 23",
      "caption": null
    },
    {
      "src": "/images/photos/gujranwala%20pilot%20project%202025%20fall%20evaluation%20team/ssss.jpeg",
      "alt": "gujranwala pilot project 2025 fall evaluation team event photograph 24",
      "caption": null
    }
  ],
  "photos/Gujranwala pilot project training session": [
    {
      "src": "/images/photos/Gujranwala%20pilot%20project%20training%20session/2w2s.jpeg",
      "alt": "Gujranwala pilot project training session event photograph 1",
      "caption": null
    },
    {
      "src": "/images/photos/Gujranwala%20pilot%20project%20training%20session/13.jpeg",
      "alt": "Gujranwala pilot project training session event photograph 2",
      "caption": null
    },
    {
      "src": "/images/photos/Gujranwala%20pilot%20project%20training%20session/14.jpeg",
      "alt": "Gujranwala pilot project training session event photograph 3",
      "caption": null
    },
    {
      "src": "/images/photos/Gujranwala%20pilot%20project%20training%20session/15.jpeg",
      "alt": "Gujranwala pilot project training session event photograph 4",
      "caption": null
    },
    {
      "src": "/images/photos/Gujranwala%20pilot%20project%20training%20session/16.jpeg",
      "alt": "Gujranwala pilot project training session event photograph 5",
      "caption": null
    },
    {
      "src": "/images/photos/Gujranwala%20pilot%20project%20training%20session/18.jpeg",
      "alt": "Gujranwala pilot project training session event photograph 6",
      "caption": null
    },
    {
      "src": "/images/photos/Gujranwala%20pilot%20project%20training%20session/44444.jpeg",
      "alt": "Gujranwala pilot project training session event photograph 7",
      "caption": null
    },
    {
      "src": "/images/photos/Gujranwala%20pilot%20project%20training%20session/1212131.jpeg",
      "alt": "Gujranwala pilot project training session event photograph 8",
      "caption": null
    },
    {
      "src": "/images/photos/Gujranwala%20pilot%20project%20training%20session/dwedw.jpeg",
      "alt": "Gujranwala pilot project training session event photograph 9",
      "caption": null
    },
    {
      "src": "/images/photos/Gujranwala%20pilot%20project%20training%20session/Screenshot%202026-08-16%20112421.png",
      "alt": "Gujranwala pilot project training session event photograph 10",
      "caption": null
    },
    {
      "src": "/images/photos/Gujranwala%20pilot%20project%20training%20session/swdw.jpeg",
      "alt": "Gujranwala pilot project training session event photograph 11",
      "caption": null
    },
    {
      "src": "/images/photos/Gujranwala%20pilot%20project%20training%20session/wwded.jpeg",
      "alt": "Gujranwala pilot project training session event photograph 12",
      "caption": null
    }
  ],
  "photos/Gujranwala refresher training jan 2026": [
    {
      "src": "/images/photos/Gujranwala%20refresher%20training%20jan%202026/1.jpeg",
      "alt": "Gujranwala refresher training jan 2026 event photograph 1",
      "caption": null
    },
    {
      "src": "/images/photos/Gujranwala%20refresher%20training%20jan%202026/2.jpeg",
      "alt": "Gujranwala refresher training jan 2026 event photograph 2",
      "caption": null
    },
    {
      "src": "/images/photos/Gujranwala%20refresher%20training%20jan%202026/3.jpeg",
      "alt": "Gujranwala refresher training jan 2026 event photograph 3",
      "caption": null
    },
    {
      "src": "/images/photos/Gujranwala%20refresher%20training%20jan%202026/4.jpeg",
      "alt": "Gujranwala refresher training jan 2026 event photograph 4",
      "caption": null
    },
    {
      "src": "/images/photos/Gujranwala%20refresher%20training%20jan%202026/5.jpeg",
      "alt": "Gujranwala refresher training jan 2026 event photograph 5",
      "caption": null
    },
    {
      "src": "/images/photos/Gujranwala%20refresher%20training%20jan%202026/6.jpeg",
      "alt": "Gujranwala refresher training jan 2026 event photograph 6",
      "caption": null
    },
    {
      "src": "/images/photos/Gujranwala%20refresher%20training%20jan%202026/7.jpeg",
      "alt": "Gujranwala refresher training jan 2026 event photograph 7",
      "caption": null
    },
    {
      "src": "/images/photos/Gujranwala%20refresher%20training%20jan%202026/8.jpeg",
      "alt": "Gujranwala refresher training jan 2026 event photograph 8",
      "caption": null
    },
    {
      "src": "/images/photos/Gujranwala%20refresher%20training%20jan%202026/9.jpeg",
      "alt": "Gujranwala refresher training jan 2026 event photograph 9",
      "caption": null
    },
    {
      "src": "/images/photos/Gujranwala%20refresher%20training%20jan%202026/10.jpeg",
      "alt": "Gujranwala refresher training jan 2026 event photograph 10",
      "caption": null
    },
    {
      "src": "/images/photos/Gujranwala%20refresher%20training%20jan%202026/11.jpeg",
      "alt": "Gujranwala refresher training jan 2026 event photograph 11",
      "caption": null
    },
    {
      "src": "/images/photos/Gujranwala%20refresher%20training%20jan%202026/12.jpeg",
      "alt": "Gujranwala refresher training jan 2026 event photograph 12",
      "caption": null
    }
  ],
  "photos/Jolly experience day chris": [
    {
      "src": "/images/photos/Jolly%20experience%20day%20chris/1.jpeg",
      "alt": "Jolly experience day chris event photograph 1",
      "caption": null
    },
    {
      "src": "/images/photos/Jolly%20experience%20day%20chris/2.jpeg",
      "alt": "Jolly experience day chris event photograph 2",
      "caption": null
    },
    {
      "src": "/images/photos/Jolly%20experience%20day%20chris/3.jpeg",
      "alt": "Jolly experience day chris event photograph 3",
      "caption": null
    },
    {
      "src": "/images/photos/Jolly%20experience%20day%20chris/4.jpeg",
      "alt": "Jolly experience day chris event photograph 4",
      "caption": null
    },
    {
      "src": "/images/photos/Jolly%20experience%20day%20chris/5.jpeg",
      "alt": "Jolly experience day chris event photograph 5",
      "caption": null
    },
    {
      "src": "/images/photos/Jolly%20experience%20day%20chris/6.jpeg",
      "alt": "Jolly experience day chris event photograph 6",
      "caption": null
    },
    {
      "src": "/images/photos/Jolly%20experience%20day%20chris/7.jpeg",
      "alt": "Jolly experience day chris event photograph 7",
      "caption": null
    },
    {
      "src": "/images/photos/Jolly%20experience%20day%20chris/8.jpeg",
      "alt": "Jolly experience day chris event photograph 8",
      "caption": null
    },
    {
      "src": "/images/photos/Jolly%20experience%20day%20chris/9.jpeg",
      "alt": "Jolly experience day chris event photograph 9",
      "caption": null
    },
    {
      "src": "/images/photos/Jolly%20experience%20day%20chris/10.jpeg",
      "alt": "Jolly experience day chris event photograph 10",
      "caption": null
    },
    {
      "src": "/images/photos/Jolly%20experience%20day%20chris/13.jpeg",
      "alt": "Jolly experience day chris event photograph 11",
      "caption": null
    },
    {
      "src": "/images/photos/Jolly%20experience%20day%20chris/15.jpeg",
      "alt": "Jolly experience day chris event photograph 12",
      "caption": null
    },
    {
      "src": "/images/photos/Jolly%20experience%20day%20chris/16.jpeg",
      "alt": "Jolly experience day chris event photograph 13",
      "caption": null
    },
    {
      "src": "/images/photos/Jolly%20experience%20day%20chris/17.jpeg",
      "alt": "Jolly experience day chris event photograph 14",
      "caption": null
    },
    {
      "src": "/images/photos/Jolly%20experience%20day%20chris/a.jpeg",
      "alt": "Jolly experience day chris event photograph 15",
      "caption": null
    },
    {
      "src": "/images/photos/Jolly%20experience%20day%20chris/b.jpeg",
      "alt": "Jolly experience day chris event photograph 16",
      "caption": null
    },
    {
      "src": "/images/photos/Jolly%20experience%20day%20chris/e.jpeg",
      "alt": "Jolly experience day chris event photograph 17",
      "caption": null
    },
    {
      "src": "/images/photos/Jolly%20experience%20day%20chris/s.jpeg",
      "alt": "Jolly experience day chris event photograph 18",
      "caption": null
    },
    {
      "src": "/images/photos/Jolly%20experience%20day%20chris/t.jpeg",
      "alt": "Jolly experience day chris event photograph 19",
      "caption": null
    },
    {
      "src": "/images/photos/Jolly%20experience%20day%20chris/u.jpeg",
      "alt": "Jolly experience day chris event photograph 20",
      "caption": null
    },
    {
      "src": "/images/photos/Jolly%20experience%20day%20chris/v.jpeg",
      "alt": "Jolly experience day chris event photograph 21",
      "caption": null
    },
    {
      "src": "/images/photos/Jolly%20experience%20day%20chris/w.jpeg",
      "alt": "Jolly experience day chris event photograph 22",
      "caption": null
    },
    {
      "src": "/images/photos/Jolly%20experience%20day%20chris/WhatsApp%20Image%202026-08-13%20at%2012.57.02%20PM.jpeg",
      "alt": "Jolly experience day chris event photograph 23",
      "caption": null
    },
    {
      "src": "/images/photos/Jolly%20experience%20day%20chris/x.jpeg",
      "alt": "Jolly experience day chris event photograph 24",
      "caption": null
    },
    {
      "src": "/images/photos/Jolly%20experience%20day%20chris/y.jpeg",
      "alt": "Jolly experience day chris event photograph 25",
      "caption": null
    }
  ],
  "photos/jolly phonics day morning lahore 2025": [
    {
      "src": "/images/photos/jolly%20phonics%20day%20morning%20lahore%202025/1.jpeg",
      "alt": "jolly phonics day morning lahore 2025 event photograph 1",
      "caption": null
    },
    {
      "src": "/images/photos/jolly%20phonics%20day%20morning%20lahore%202025/18.jpeg",
      "alt": "jolly phonics day morning lahore 2025 event photograph 2",
      "caption": null
    },
    {
      "src": "/images/photos/jolly%20phonics%20day%20morning%20lahore%202025/19.jpeg",
      "alt": "jolly phonics day morning lahore 2025 event photograph 3",
      "caption": null
    },
    {
      "src": "/images/photos/jolly%20phonics%20day%20morning%20lahore%202025/20.jpeg",
      "alt": "jolly phonics day morning lahore 2025 event photograph 4",
      "caption": null
    },
    {
      "src": "/images/photos/jolly%20phonics%20day%20morning%20lahore%202025/21.jpeg",
      "alt": "jolly phonics day morning lahore 2025 event photograph 5",
      "caption": null
    },
    {
      "src": "/images/photos/jolly%20phonics%20day%20morning%20lahore%202025/22.jpeg",
      "alt": "jolly phonics day morning lahore 2025 event photograph 6",
      "caption": null
    },
    {
      "src": "/images/photos/jolly%20phonics%20day%20morning%20lahore%202025/23.jpeg",
      "alt": "jolly phonics day morning lahore 2025 event photograph 7",
      "caption": null
    },
    {
      "src": "/images/photos/jolly%20phonics%20day%20morning%20lahore%202025/24.jpeg",
      "alt": "jolly phonics day morning lahore 2025 event photograph 8",
      "caption": null
    },
    {
      "src": "/images/photos/jolly%20phonics%20day%20morning%20lahore%202025/25.jpeg",
      "alt": "jolly phonics day morning lahore 2025 event photograph 9",
      "caption": null
    },
    {
      "src": "/images/photos/jolly%20phonics%20day%20morning%20lahore%202025/26.jpeg",
      "alt": "jolly phonics day morning lahore 2025 event photograph 10",
      "caption": null
    },
    {
      "src": "/images/photos/jolly%20phonics%20day%20morning%20lahore%202025/27.jpeg",
      "alt": "jolly phonics day morning lahore 2025 event photograph 11",
      "caption": null
    },
    {
      "src": "/images/photos/jolly%20phonics%20day%20morning%20lahore%202025/30.jpeg",
      "alt": "jolly phonics day morning lahore 2025 event photograph 12",
      "caption": null
    },
    {
      "src": "/images/photos/jolly%20phonics%20day%20morning%20lahore%202025/32.jpeg",
      "alt": "jolly phonics day morning lahore 2025 event photograph 13",
      "caption": null
    },
    {
      "src": "/images/photos/jolly%20phonics%20day%20morning%20lahore%202025/33.jpeg",
      "alt": "jolly phonics day morning lahore 2025 event photograph 14",
      "caption": null
    },
    {
      "src": "/images/photos/jolly%20phonics%20day%20morning%20lahore%202025/34.jpeg",
      "alt": "jolly phonics day morning lahore 2025 event photograph 15",
      "caption": null
    },
    {
      "src": "/images/photos/jolly%20phonics%20day%20morning%20lahore%202025/35.jpeg",
      "alt": "jolly phonics day morning lahore 2025 event photograph 16",
      "caption": null
    }
  ],
  "photos/karachi pilot project training": [
    {
      "src": "/images/photos/karachi%20pilot%20project%20training/1.jpeg",
      "alt": "karachi pilot project training event photograph 1",
      "caption": null
    },
    {
      "src": "/images/photos/karachi%20pilot%20project%20training/2.jpeg",
      "alt": "karachi pilot project training event photograph 2",
      "caption": null
    },
    {
      "src": "/images/photos/karachi%20pilot%20project%20training/3.jpeg",
      "alt": "karachi pilot project training event photograph 3",
      "caption": null
    },
    {
      "src": "/images/photos/karachi%20pilot%20project%20training/4.jpeg",
      "alt": "karachi pilot project training event photograph 4",
      "caption": null
    },
    {
      "src": "/images/photos/karachi%20pilot%20project%20training/19.jpeg",
      "alt": "karachi pilot project training event photograph 5",
      "caption": null
    },
    {
      "src": "/images/photos/karachi%20pilot%20project%20training/20.jpeg",
      "alt": "karachi pilot project training event photograph 6",
      "caption": null
    }
  ],
  "photos/KIPS school training lake city branch training summer 2026": [
    {
      "src": "/images/photos/KIPS%20school%20training%20lake%20city%20branch%20training%20summer%202026/kips%20training/a.jpeg",
      "alt": "KIPS school training lake city branch training summer 2026 event photograph 1",
      "caption": null
    },
    {
      "src": "/images/photos/KIPS%20school%20training%20lake%20city%20branch%20training%20summer%202026/kips%20training/b.jpeg",
      "alt": "KIPS school training lake city branch training summer 2026 event photograph 2",
      "caption": null
    },
    {
      "src": "/images/photos/KIPS%20school%20training%20lake%20city%20branch%20training%20summer%202026/kips%20training/c.jpeg",
      "alt": "KIPS school training lake city branch training summer 2026 event photograph 3",
      "caption": null
    },
    {
      "src": "/images/photos/KIPS%20school%20training%20lake%20city%20branch%20training%20summer%202026/kips%20training/d.jpeg",
      "alt": "KIPS school training lake city branch training summer 2026 event photograph 4",
      "caption": null
    },
    {
      "src": "/images/photos/KIPS%20school%20training%20lake%20city%20branch%20training%20summer%202026/kips%20training/e.jpeg",
      "alt": "KIPS school training lake city branch training summer 2026 event photograph 5",
      "caption": null
    },
    {
      "src": "/images/photos/KIPS%20school%20training%20lake%20city%20branch%20training%20summer%202026/kips%20training/f.jpeg",
      "alt": "KIPS school training lake city branch training summer 2026 event photograph 6",
      "caption": null
    },
    {
      "src": "/images/photos/KIPS%20school%20training%20lake%20city%20branch%20training%20summer%202026/kips%20training/g.jpeg",
      "alt": "KIPS school training lake city branch training summer 2026 event photograph 7",
      "caption": null
    },
    {
      "src": "/images/photos/KIPS%20school%20training%20lake%20city%20branch%20training%20summer%202026/kips%20training/h.jpeg",
      "alt": "KIPS school training lake city branch training summer 2026 event photograph 8",
      "caption": null
    },
    {
      "src": "/images/photos/KIPS%20school%20training%20lake%20city%20branch%20training%20summer%202026/kips%20training/i.jpeg",
      "alt": "KIPS school training lake city branch training summer 2026 event photograph 9",
      "caption": null
    },
    {
      "src": "/images/photos/KIPS%20school%20training%20lake%20city%20branch%20training%20summer%202026/kips%20training/j.jpeg",
      "alt": "KIPS school training lake city branch training summer 2026 event photograph 10",
      "caption": null
    },
    {
      "src": "/images/photos/KIPS%20school%20training%20lake%20city%20branch%20training%20summer%202026/kips%20training/k.jpeg",
      "alt": "KIPS school training lake city branch training summer 2026 event photograph 11",
      "caption": null
    },
    {
      "src": "/images/photos/KIPS%20school%20training%20lake%20city%20branch%20training%20summer%202026/kips%20training/l.jpeg",
      "alt": "KIPS school training lake city branch training summer 2026 event photograph 12",
      "caption": null
    },
    {
      "src": "/images/photos/KIPS%20school%20training%20lake%20city%20branch%20training%20summer%202026/kips%20training/m.jpeg",
      "alt": "KIPS school training lake city branch training summer 2026 event photograph 13",
      "caption": null
    },
    {
      "src": "/images/photos/KIPS%20school%20training%20lake%20city%20branch%20training%20summer%202026/kips%20training/n.jpeg",
      "alt": "KIPS school training lake city branch training summer 2026 event photograph 14",
      "caption": null
    },
    {
      "src": "/images/photos/KIPS%20school%20training%20lake%20city%20branch%20training%20summer%202026/kips%20training/o.jpeg",
      "alt": "KIPS school training lake city branch training summer 2026 event photograph 15",
      "caption": null
    },
    {
      "src": "/images/photos/KIPS%20school%20training%20lake%20city%20branch%20training%20summer%202026/kips%20training/p.jpeg",
      "alt": "KIPS school training lake city branch training summer 2026 event photograph 16",
      "caption": null
    },
    {
      "src": "/images/photos/KIPS%20school%20training%20lake%20city%20branch%20training%20summer%202026/kips%20training/q.jpeg",
      "alt": "KIPS school training lake city branch training summer 2026 event photograph 17",
      "caption": null
    },
    {
      "src": "/images/photos/KIPS%20school%20training%20lake%20city%20branch%20training%20summer%202026/kips%20training/r.jpeg",
      "alt": "KIPS school training lake city branch training summer 2026 event photograph 18",
      "caption": null
    },
    {
      "src": "/images/photos/KIPS%20school%20training%20lake%20city%20branch%20training%20summer%202026/kips%20training/s.jpeg",
      "alt": "KIPS school training lake city branch training summer 2026 event photograph 19",
      "caption": null
    },
    {
      "src": "/images/photos/KIPS%20school%20training%20lake%20city%20branch%20training%20summer%202026/kips%20training/t.jpeg",
      "alt": "KIPS school training lake city branch training summer 2026 event photograph 20",
      "caption": null
    }
  ],
  "photos/Lahore pilot project evaluation team schools": [
    {
      "src": "/images/photos/Lahore%20pilot%20project%20evaluation%20team%20schools/1.jpeg",
      "alt": "Lahore pilot project evaluation team schools event photograph 1",
      "caption": null
    },
    {
      "src": "/images/photos/Lahore%20pilot%20project%20evaluation%20team%20schools/2.jpeg",
      "alt": "Lahore pilot project evaluation team schools event photograph 2",
      "caption": null
    },
    {
      "src": "/images/photos/Lahore%20pilot%20project%20evaluation%20team%20schools/3.jpeg",
      "alt": "Lahore pilot project evaluation team schools event photograph 3",
      "caption": null
    }
  ],
  "photos/lahore pilot project training sessions": [
    {
      "src": "/images/photos/lahore%20pilot%20project%20training%20sessions/1.jpeg",
      "alt": "lahore pilot project training sessions event photograph 1",
      "caption": null
    },
    {
      "src": "/images/photos/lahore%20pilot%20project%20training%20sessions/2.jpeg",
      "alt": "lahore pilot project training sessions event photograph 2",
      "caption": null
    },
    {
      "src": "/images/photos/lahore%20pilot%20project%20training%20sessions/3.jpeg",
      "alt": "lahore pilot project training sessions event photograph 3",
      "caption": null
    },
    {
      "src": "/images/photos/lahore%20pilot%20project%20training%20sessions/4.jpeg",
      "alt": "lahore pilot project training sessions event photograph 4",
      "caption": null
    },
    {
      "src": "/images/photos/lahore%20pilot%20project%20training%20sessions/5.jpeg",
      "alt": "lahore pilot project training sessions event photograph 5",
      "caption": null
    },
    {
      "src": "/images/photos/lahore%20pilot%20project%20training%20sessions/Nscoe%20lahore%20training%20day%202%20august%202025/1.jpeg",
      "alt": "lahore pilot project training sessions event photograph 6",
      "caption": null
    },
    {
      "src": "/images/photos/lahore%20pilot%20project%20training%20sessions/Nscoe%20lahore%20training%20day%202%20august%202025/2.jpeg",
      "alt": "lahore pilot project training sessions event photograph 7",
      "caption": null
    },
    {
      "src": "/images/photos/lahore%20pilot%20project%20training%20sessions/Nscoe%20lahore%20training%20day%202%20august%202025/3.jpeg",
      "alt": "lahore pilot project training sessions event photograph 8",
      "caption": null
    },
    {
      "src": "/images/photos/lahore%20pilot%20project%20training%20sessions/Nscoe%20lahore%20training%20day%202%20august%202025/4.jpeg",
      "alt": "lahore pilot project training sessions event photograph 9",
      "caption": null
    },
    {
      "src": "/images/photos/lahore%20pilot%20project%20training%20sessions/nscoe%20pilot%20project%20training%20%20august%202025/1.jpeg",
      "alt": "lahore pilot project training sessions event photograph 10",
      "caption": null
    },
    {
      "src": "/images/photos/lahore%20pilot%20project%20training%20sessions/nscoe%20pilot%20project%20training%20%20august%202025/2.jpeg",
      "alt": "lahore pilot project training sessions event photograph 11",
      "caption": null
    },
    {
      "src": "/images/photos/lahore%20pilot%20project%20training%20sessions/nscoe%20pilot%20project%20training%20%20august%202025/3.jpeg",
      "alt": "lahore pilot project training sessions event photograph 12",
      "caption": null
    },
    {
      "src": "/images/photos/lahore%20pilot%20project%20training%20sessions/nscoe%20pilot%20project%20training%20%20august%202025/4.jpeg",
      "alt": "lahore pilot project training sessions event photograph 13",
      "caption": null
    },
    {
      "src": "/images/photos/lahore%20pilot%20project%20training%20sessions/nscoe%20pilot%20project%20training%20%20august%202025/5.jpeg",
      "alt": "lahore pilot project training sessions event photograph 14",
      "caption": null
    },
    {
      "src": "/images/photos/lahore%20pilot%20project%20training%20sessions/nscoe%20pilot%20project%20training%20%20august%202025/6.jpeg",
      "alt": "lahore pilot project training sessions event photograph 15",
      "caption": null
    },
    {
      "src": "/images/photos/lahore%20pilot%20project%20training%20sessions/nscoe%20pilot%20project%20training%20%20august%202025/7.jpeg",
      "alt": "lahore pilot project training sessions event photograph 16",
      "caption": null
    },
    {
      "src": "/images/photos/lahore%20pilot%20project%20training%20sessions/nscoe%20pilot%20project%20training%20%20august%202025/8.jpeg",
      "alt": "lahore pilot project training sessions event photograph 17",
      "caption": null
    },
    {
      "src": "/images/photos/lahore%20pilot%20project%20training%20sessions/nscoe%20pilot%20project%20training%20%20august%202025/9.jpeg",
      "alt": "lahore pilot project training sessions event photograph 18",
      "caption": null
    },
    {
      "src": "/images/photos/lahore%20pilot%20project%20training%20sessions/nscoe%20pilot%20project%20training%20%20august%202025/10.jpeg",
      "alt": "lahore pilot project training sessions event photograph 19",
      "caption": null
    },
    {
      "src": "/images/photos/lahore%20pilot%20project%20training%20sessions/nscoe%20pilot%20project%20training%20%20august%202025/11.jpeg",
      "alt": "lahore pilot project training sessions event photograph 20",
      "caption": null
    },
    {
      "src": "/images/photos/lahore%20pilot%20project%20training%20sessions/nscoe%20pilot%20project%20training%20%20august%202025/12.jpeg",
      "alt": "lahore pilot project training sessions event photograph 21",
      "caption": null
    },
    {
      "src": "/images/photos/lahore%20pilot%20project%20training%20sessions/nscoe%20pilot%20project%20training%20%20august%202025/13.jpeg",
      "alt": "lahore pilot project training sessions event photograph 22",
      "caption": null
    },
    {
      "src": "/images/photos/lahore%20pilot%20project%20training%20sessions/nscoe%20pilot%20project%20training%20%20august%202025/14.jpeg",
      "alt": "lahore pilot project training sessions event photograph 23",
      "caption": null
    },
    {
      "src": "/images/photos/lahore%20pilot%20project%20training%20sessions/nscoe%20pilot%20project%20training%20%20august%202025/15.jpeg",
      "alt": "lahore pilot project training sessions event photograph 24",
      "caption": null
    },
    {
      "src": "/images/photos/lahore%20pilot%20project%20training%20sessions/nscoe%20pilot%20project%20training%20%20august%202025/16.jpeg",
      "alt": "lahore pilot project training sessions event photograph 25",
      "caption": null
    },
    {
      "src": "/images/photos/lahore%20pilot%20project%20training%20sessions/nscoe%20pilot%20project%20training%20%20august%202025/17.jpeg",
      "alt": "lahore pilot project training sessions event photograph 26",
      "caption": null
    },
    {
      "src": "/images/photos/lahore%20pilot%20project%20training%20sessions/nscoe%20pilot%20project%20training%20%20august%202025/18.jpeg",
      "alt": "lahore pilot project training sessions event photograph 27",
      "caption": null
    },
    {
      "src": "/images/photos/lahore%20pilot%20project%20training%20sessions/nscoe%20pilot%20project%20training%20%20august%202025/19.jpeg",
      "alt": "lahore pilot project training sessions event photograph 28",
      "caption": null
    },
    {
      "src": "/images/photos/lahore%20pilot%20project%20training%20sessions/nscoe%20pilot%20project%20training%20%20august%202025/20.jpeg",
      "alt": "lahore pilot project training sessions event photograph 29",
      "caption": null
    },
    {
      "src": "/images/photos/lahore%20pilot%20project%20training%20sessions/nscoe%20pilot%20project%20training%20%20august%202025/21.jpeg",
      "alt": "lahore pilot project training sessions event photograph 30",
      "caption": null
    }
  ],
  "photos/Lahore spring 2026 training starfish": [
    {
      "src": "/images/photos/Lahore%20spring%202026%20training%20starfish/5.jpeg",
      "alt": "Lahore spring 2026 training starfish event photograph 1",
      "caption": null
    }
  ],
  "photos/Soar stem school system": [
    {
      "src": "/images/photos/Soar%20stem%20school%20system/1.jpeg",
      "alt": "Soar stem school system event photograph 1",
      "caption": null
    },
    {
      "src": "/images/photos/Soar%20stem%20school%20system/2.jpeg",
      "alt": "Soar stem school system event photograph 2",
      "caption": null
    },
    {
      "src": "/images/photos/Soar%20stem%20school%20system/3.jpeg",
      "alt": "Soar stem school system event photograph 3",
      "caption": null
    },
    {
      "src": "/images/photos/Soar%20stem%20school%20system/4.jpeg",
      "alt": "Soar stem school system event photograph 4",
      "caption": null
    }
  ]
}
