import { z } from 'zod'

export const courseSchema = z.object({
  title: z.string().min(2),
  slug: z.string().min(2).regex(/^[a-z0-9-]+$/),
  subtitle: z.string().optional(),
  description: z.string().optional(),
  rich_description: z.string().optional(),
  excerpt: z.string().optional(),
  price: z.coerce.number().min(0),
  discounted_price: z.coerce.number().min(0).optional().nullable(),
  currency: z.string().min(3).max(3).default('PKR'),
  category: z.string().min(1),
  level: z.string().default('beginner'),
  language: z.string().default('English'),
  duration: z.string().optional(),
  instructor: z.string().optional(),
  instructor_bio: z.string().optional(),
  image_url: z.string().optional().nullable(),
  thumbnail_url: z.string().optional().nullable(),
  banner_url: z.string().optional().nullable(),
  instructor_image_url: z.string().optional().nullable(),
  certificate_background_url: z.string().optional().nullable(),
  hero_video_url: z.string().optional().nullable(),
  enrolment_opens_at: z.string().optional().nullable(),
  enrolment_closes_at: z.string().optional().nullable(),
  max_students: z.coerce.number().int().positive().optional().nullable(),
  access_duration_days: z.coerce.number().int().positive().default(90),
  required_online_minutes: z.coerce.number().int().min(0).default(0),
  required_offline_minutes: z.coerce.number().int().min(0).default(0),
  passing_quiz_percentage: z.coerce.number().int().min(0).max(100).default(70),
  required_assignment_passes: z.coerce.number().int().min(0).default(0),
  daily_online_minutes_cap: z.coerce.number().int().positive().default(480),
  inactivity_timeout_seconds: z.coerce.number().int().min(180).max(300).default(240),
  max_offline_entry_minutes: z.coerce.number().int().positive().default(360),
  objectives: z.string().optional(),
  requirements: z.string().optional(),
  seo_title: z.string().optional(),
  seo_description: z.string().optional(),
  featured: z.coerce.boolean().default(false),
  published: z.coerce.boolean().default(true),
  certificate_enabled: z.coerce.boolean().default(true),
  completion_requires_lessons: z.coerce.boolean().default(true),
  completion_requires_online_minutes: z.coerce.boolean().default(false),
  completion_requires_offline_minutes: z.coerce.boolean().default(false),
  completion_requires_quiz: z.coerce.boolean().default(false),
  completion_requires_assignments: z.coerce.boolean().default(false),
  completion_requires_active_enrollment: z.coerce.boolean().default(true),
  completion_requires_instructor_approval: z.coerce.boolean().default(false),
  offline_evidence_required: z.coerce.boolean().default(false),
})

export type CourseInput = z.infer<typeof courseSchema>
