import { z } from 'zod'

export const courseSchema = z.object({
  title: z.string().trim().min(2, 'Course title must be at least 2 characters.'),
  slug: z
    .string()
    .trim()
    .min(2, 'Course slug must be at least 2 characters.')
    .regex(/^[a-z0-9-]+$/, 'Slug can only use lowercase letters, numbers, and hyphens. Example: jolly-phonics-free-course.'),
  subtitle: z.string().optional(),
  description: z.string().optional(),
  rich_description: z.string().optional(),
  excerpt: z.string().optional(),
  price: z.coerce.number().min(0, 'Price cannot be negative. Use 0 for a free course.'),
  discounted_price: z.coerce.number().min(0, 'Discounted price cannot be negative.').optional().nullable(),
  currency: z.string().trim().min(3, 'Use a 3-letter currency code such as PKR.').max(3, 'Use a 3-letter currency code such as PKR.').default('PKR'),
  category: z.string().min(1, 'Choose a course category.'),
  level: z.string().default('beginner'),
  language: z.string().default('English'),
  duration: z.string().optional(),
  instructor: z.string().optional(),
  instructor_bio: z.string().optional(),
  image_url: z.string().optional().nullable(),
  thumbnail_url: z.string().optional().nullable(),
  banner_url: z.string().optional().nullable(),
  instructor_image_url: z.string().optional().nullable(),
  certificate_background_url: z.string().optional().nullable(),
  hero_video_url: z.string().optional().nullable(),
  enrolment_opens_at: z.string().optional().nullable(),
  enrolment_closes_at: z.string().optional().nullable(),
  max_students: z.coerce.number().int('Max students must be a whole number.').positive('Max students must be greater than 0.').optional().nullable(),
  access_duration_days: z.coerce.number().int().positive('Access duration must be at least 1 day.').default(90),
  required_online_minutes: z.coerce.number().int().min(0, 'Required online minutes cannot be negative.').default(0),
  required_offline_minutes: z.coerce.number().int().min(0, 'Required offline minutes cannot be negative.').default(0),
  passing_quiz_percentage: z.coerce.number().int().min(0).max(100, 'Passing quiz percentage must be between 0 and 100.').default(70),
  required_assignment_passes: z.coerce.number().int().min(0, 'Required assignment passes cannot be negative.').default(0),
  daily_online_minutes_cap: z.coerce.number().int().positive('Daily online cap must be greater than 0.').default(480),
  inactivity_timeout_seconds: z.coerce.number().int().min(180, 'Inactivity timeout must be at least 180 seconds.').max(300, 'Inactivity timeout cannot be more than 300 seconds.').default(240),
  max_offline_entry_minutes: z.coerce.number().int().positive('Max offline entry minutes must be greater than 0.').default(360),
  objectives: z.string().optional(),
  requirements: z.string().optional(),
  seo_title: z.string().optional(),
  seo_description: z.string().optional(),
  featured: z.coerce.boolean().default(false),
  published: z.coerce.boolean().default(true),
  visibility_status: z.enum(['draft', 'published', 'unlisted', 'archived']).default('published'),
  enrollment_status: z.enum(['open', 'closed', 'coming_soon']).default('open'),
  unlisted: z.coerce.boolean().default(false),
  archived: z.coerce.boolean().default(false),
  coming_soon: z.coerce.boolean().default(false),
  certificate_enabled: z.coerce.boolean().default(true),
  completion_requires_lessons: z.coerce.boolean().default(true),
  completion_requires_online_minutes: z.coerce.boolean().default(false),
  completion_requires_offline_minutes: z.coerce.boolean().default(false),
  completion_requires_quiz: z.coerce.boolean().default(false),
  completion_requires_assignments: z.coerce.boolean().default(false),
  completion_requires_active_enrollment: z.coerce.boolean().default(true),
  completion_requires_instructor_approval: z.coerce.boolean().default(false),
  offline_evidence_required: z.coerce.boolean().default(false),
})

export type CourseInput = z.infer<typeof courseSchema>
